# Generated by Django 3.2.11 on 2022-04-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
