# Generated by Django 3.2.11 on 2022-04-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220427_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default=123, upload_to=''),
            preserve_default=False,
        ),
    ]
